/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.ulalax.playhouse.kotlin-spring-application-conventions")
}

dependencies {
    implementation("org.ulalax.playhouse:playhouse:1.0")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("org.ulalax.playhouse.app.App")
//}
