/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.ulalax.playhouse.kotlin-spring-application-conventions")
    id("io.freefair.lombok")
}

dependencies {
    implementation(project(":simpleProtocol"))
    implementation("org.ulalax.playhouse:playhouse:1.0")

}

//application {
//    // Define the main class for the application.
//    mainClass.set("org.ulalax.playhouse.pl.simple.api.app")
//}
