/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("com.lifemmo.pl.base.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    id("org.springframework.boot")
    id("io.spring.dependency-management")
    kotlin("plugin.spring")

}

configurations {
    all {
        exclude(group="org.springframework.boot", module="spring-boot-starter-logging")
        //  exclude("javax.ws.rs","jsr311-api")
    }
}

configurations {
    compileOnly {
        extendsFrom(configurations.annotationProcessor.get())
    }
}

dependencies{
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter
    implementation("org.springframework.boot:spring-boot-starter")
    annotationProcessor("org.springframework.boot:spring-boot-configuration-processor")
    implementation("org.springframework.boot:spring-boot-starter-log4j2")
//    implementation("com.lifemmo.pl.base:plbase")

    testImplementation("org.springframework.boot:spring-boot-starter-test")

}