
/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    id("org.jetbrains.kotlin.jvm")
//    java
    `maven-publish`
//    id("io.freefair.lombok")
    id("com.google.protobuf")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}


tasks {
    val sourcesJar by creating(Jar::class) {
        archiveClassifier.set("sources")
        from(kotlin.sourceSets.getByName("main").kotlin.srcDirs)
    }

    artifacts {
        archives(sourcesJar)
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions {
        jvmTarget = "11"
    }
}


dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.9")
    }

    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
   // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
    // https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4")
    // https://mvnrepository.com/artifact/com.github.ben-manes.caffeine/caffeine
    implementation("com.github.ben-manes.caffeine:caffeine:3.1.1")



    implementation(Depend.protoBuf)
    implementation(Depend.log4JApiKotlin)
    implementation(Depend.log4JApi)
    implementation(Depend.log4JCore)
    implementation(Depend.nettyBuffer)
    implementation(Depend.commonLang3)

    // Use JUnit Jupiter for testing.
    testImplementation(Depend.junitJupiter)
    // https://mvnrepository.com/artifact/org.assertj/assertj-core
    testImplementation("org.assertj:assertj-core:3.23.1")

}




tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    systemProperty("file.encoding", "utf-8")
    useJUnitPlatform()
    testLogging{
        events("PASSED", "SKIPPED", "FAILED", "STANDARD_OUT", "STANDARD_ERROR")
    }
}
