/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
   //implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20")
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.22")

    implementation("com.google.protobuf:protobuf-gradle-plugin:0.8.19")

    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.0.6")
    implementation("io.spring.gradle:dependency-management-plugin:1.1.0")
   //implementation("org.jetbrains.kotlin:kotlin-allopen:1.8.20")
// https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-allopen
    implementation("org.jetbrains.kotlin:kotlin-allopen:1.7.22")

}
