/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.10")
    implementation("com.google.protobuf:protobuf-gradle-plugin:0.8.19")

    implementation("org.springframework.boot:spring-boot-gradle-plugin:2.7.3")
    implementation("io.spring.gradle:dependency-management-plugin:1.0.13.RELEASE")
    implementation("org.jetbrains.kotlin:kotlin-allopen:1.6.21")

    implementation("io.freefair.gradle:lombok-plugin:6.5.1")
//    implementation("com.lifemmo.pl.base:plbase:1.0")
}
