/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.lifemmo.pl.base.kotlin-spring-application-conventions")
}

dependencies {
    implementation(project(":simpleProtocol"))
    implementation("org.apache.commons:commons-text")
    implementation("com.lifemmo.pl.base:clientConnector:1.0")


}

//application {
//    // Define the main class for the application.
//    mainClass.set("com.lifemmo.pl.base.app.App")
//}
